### PR TITLE
Adding in answerCoding to Clinical Baseline

### PR DESCRIPTION
**Pull request by MariekeSpanFurore**
I've added in answerCoding instead of answerStrings into the baseline clinical response questionnaire. I've used UUIDs to create a CodeSystem. There are no errors or warnings, but the QA report does return many hints since the Codesystem is unknown and can therefore not be validated. As discussed previously, we will ignore this because it serves the purpose.

### CODE REVIEW

**Review by vadi2 — APPROVED** [review]
👍 added patient baseline as well.

**Comment by vadi2** [comment]
Could you fix other questionnaires (after the connectathon) before merging? so we don't forget

**Comment by MariekeSpanFurore** [comment]
Thanks! Yes I'll do that.

**Review by vadi2 — APPROVED** [review]
👍

**Pull request merged**
