### PR TITLE
Update AJCC (copyrights and codes)

### PR DESCRIPTION
**Pull request by MariekeSpanFurore**

### CODE REVIEW

**Review by vadi2 — COMMENTED** [review]
This branch has a build error -

```
error Resolved value "RecurrenceMethodVS" is not a valid URI.
  File: /Users/320128457/Programs/BreastCancer-ICHOM/input/fsh/Profiles clinical datapoints/Condition.fsh
  Line: 96
```

**Comment by vadi2** [comment]
Why is this one closed?

**Comment by MariekeSpanFurore** [comment]
I am not so sure anymore. I thought I already merged it in, but I guess I was confused with all the other PRs I created. I will restore this PR, as it is ready to be merged in.

**Review by vadi2 — APPROVED** [review]
Yup - it's better to focus one PR on one type of change for this reason.

**Review by vadi2 — APPROVED** [review]

**Pull request merged**
