### PR TITLE
Rename Death BC profile

### PR DESCRIPTION
**Pull request by vadi2**
Rename Death BC profile to be more intuitive.

### CODE REVIEW

**Comment by MariekeSpanFurore** [comment]
Just a suggestion, we can also call it: Vital status

**Comment by vadi2** [comment]
Hmm, I'm not sure that connects. This is for the Observation that death was due to cancer?

**Comment by vadi2** [comment]
@MariekeSpanFurore ping

**Comment by MariekeSpanFurore** [comment]
I see, I think it's fine this way. Vital status is another element which is in the patient profile, so this is the best option.

**Pull request merged**
