### PR TITLE
fix bodyweight/bodyheight slice error

### PR DESCRIPTION
**Pull request by davidfurore**
fix error "The slice definition has min of 0 but add up to 1..."

### CODE REVIEW

**Comment by davidfurore** [comment]
@vadi2  
Hi Vadim,
are you able to review this pull request?

**Review by vadi2 — APPROVED** [review]

**Comment by davidfurore** [comment]
@vadi2 
Thanks! Could you also merge this pull request (I don't have write access yet)

**Comment by vadi2** [comment]
Aha - you would need to reach out to HL7 to get commit access. Marieke would know, she did it last

**Comment by davidfurore** [comment]
Thanks! I will do that

**Pull request merged**
